---
- name: Verifying beats files
  hosts: elk
  vars:
    files:
      - filebeat
      - metricbeat

  tasks:

  - name: Checking if file is present
    stat:
      path: "/etc/{{ item }}/{{ item }}.yml"
    with_items: "{{ files }}"
    register: status

  - name: Reporting if file exists
    debug:
      msg: "{{ item.item }} exists"
    with_items: "{{ status.results }}"
    when: item.stat.exists

  - name: Copying from server if file not found
    copy:
      src: "~/ansible/files/{{ item.item }}.yml"
      dest: "/etc/{{ item.item }}/{{ item.item }}.yml"
    with_items: "{{ status.results }}"
    when: not item.stat.exists

